import type { Metadata } from 'next'
import { Aside } from '@/ui'
import { ClubMenu } from './_elements/ClubMenu/ClubMenu'

export const metadata: Metadata = {
  title: 'Club',
  description: 'Generated by create next app',
}

export default function ClubLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Aside>
        <ClubMenu />
      </Aside>

      {children}

      <Aside> </Aside>
    </>
  )
}
