import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { RightSidebar, ClubMenu } from './_elements'

export const metadata: Metadata = {
  title: 'Club',
  description: 'Generated by create next app',
}

export default function ClubLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <ClubMenu />
      {children}
      <RightSidebar />
    </>
  )
}
