export type Size = 'small' | 'medium' | 'large'
export type Color =
  | 'primary'
  | 'secondary'
  | 'success'
  | 'warning'
  | 'error'
  | 'info'
export type Variant = 'text' | 'outlined' | 'contained'
export type fontVariants = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p'
