export enum Langs {
  RU = 'ru',
  EN = 'en',
}

export type Translation = {
  [key in TranslationKeys]: string
}

export type Translate = {
  en: Translation
  ru: Translation
}

export const translate = {
  en: {
    admin: 'Admin',
    add: 'Add',
    dashboard: 'Dashboard',
    login: 'Login',
    registration: 'Registration',
    home: 'Home',
    shop: 'Shop',
    products: 'Products',
    tea: 'Tea',
    coffee: 'Coffee',
    favorites: 'Favorites',
    compare: 'Compare',
    cart: 'Cart',
    blog: 'Blog',
    club: 'Club',
    account: 'Account',
    lk: 'Personal Area',
    search: 'Search',
    logout: 'Logout',
    darkTheme: 'Dark theme',
    lightTheme: 'Light theme',
    sorting: 'Sorting',
    new: 'New',
    pop: 'Pop',
    priceAsc: 'Price asc',
    priceDesc: 'Price desc',
    required: 'Required',
    title: 'Title',
    description: 'Description',
    inStock: 'In stock',
    volume: 'Volume',
    price: 'Price',
    image: 'Image',
    images: 'Images',
    save: 'Save',
    delete: 'Delete',
    newProduct: 'New product',
    maxSize: 'Max size',
    MaxLimit: 'Max limit',
    more0: 'Need more than 0',
    published: 'Published',
  },
  ru: {
    admin: 'Админ',
    add: 'Добавить',
    dashboard: 'Главная панель',
    login: 'Вход',
    registration: 'Регистрация',
    home: 'Главная',
    shop: 'Магазин',
    products: 'Товары',
    tea: 'Чай',
    coffee: 'Кофе',
    favorites: 'Избранные',
    compare: 'Сравнение',
    cart: 'Корзина',
    blog: 'Блог',
    club: 'Клуб',
    account: 'Аккаунт',
    lk: 'Личный кабинет',
    search: 'Поиск',
    logout: 'Выход',
    darkTheme: 'Тёмная тема',
    lightTheme: 'Светлая тема',
    sorting: 'Сортировка',
    new: 'Новые',
    pop: 'Популярные',
    priceAsc: 'Возрастание цены',
    priceDesc: 'Убывание цены',
    required: 'Обязательно',
    title: 'Заголовок',
    description: 'Описание',
    inStock: 'В наличии',
    volume: 'Объём',
    price: 'Цена',
    image: 'Изображение',
    images: 'Изображения',
    save: 'Сохранить',
    delete: 'Удалить',
    newProduct: 'Новый товар',
    maxSize: 'Максимальный размер',
    MaxLimit: 'Максимальное количество',
    more0: 'Нужно больше 0',
    published: 'Опубликовать',
  },
}

export type TranslationKeys = keyof (typeof translate)['en']
