export enum Langs {
  RU = 'ru',
  EN = 'en',
}

export type Translation = {
  [key in TranslationKeys]: string
}

export type Translate = {
  en: Translation
  ru: Translation
}

export const translate = {
  en: {
    admin: 'Admin',
    add: 'Add',
    added: 'Added',
    addedToCart: 'Added to cart',
    addedToFavorites: 'Added to favorites',
    excludedFromFavorites: 'Excluded from favorites',
    addedToCompare: 'Added to compare',
    excludedFromCompare: 'Excluded from compare',
    dashboard: 'Dashboard',
    login: 'Login',
    registration: 'Registration',
    home: 'Home',
    shop: 'Shop',
    products: 'Products',
    tea: 'Tea',
    coffee: 'Coffee',
    favorites: 'Favorites',
    compare: 'Compare',
    cart: 'Cart',
    blog: 'Blog',
    club: 'Club',
    account: 'Account',
    lk: 'Personal Area',
    search: 'Search',
    logout: 'Logout',
    darkTheme: 'Dark theme',
    lightTheme: 'Light theme',
    sorting: 'Sorting',
    new: 'New',
    pop: 'Pop',
    priceAsc: 'Price asc',
    priceDesc: 'Price desc',
    required: 'Required',
    title: 'Title',
    description: 'Description',
    inStock: 'In stock',
    ended: 'Ended',
    volume: 'Volume',
    price: 'Price',
    image: 'Image',
    images: 'Images',
    save: 'Save',
    delete: 'Delete',
    newProduct: 'New product',
    maxSize: 'Max size',
    MaxLimit: 'Max limit',
    more0: 'Need more than 0',
    published: 'Published',
    updateProduct: 'Update product',
    reviews: 'Reviews',
    homeTitle: 'International community',
    homeDescription:
      'Welcome to the ONE community space. Here we are interested in the care of health, beauty and longevity. All users have access to such services as e-shop, blog, social network. Every day we are getting bigger. We`ll be glad to see you in the community, and help you reach your goals.',
    policy: 'Confidentiality Policy',
    cookies: 'Use of cookies',
    quantity: 'Quantity',
    cost: 'Cost',
    empty: 'Empty',
    email: 'Email',
    password: 'Password',
    send: 'Send',
    min8: 'Minimum 8 characters',
    max32: 'Maximum 8 characters',
    dontAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    invalidCredentials: 'Invalid credentials',
    maximum: 'Maximum',
    minimum: 'Minimum',
    profile: 'Profile',
  },
  ru: {
    admin: 'Админ',
    add: 'Добавить',
    added: 'Добавлено',
    addedToCart: 'Добавлено в корзину',
    addedToFavorites: 'Добавлено в избранные',
    excludedFromFavorites: 'Исключено из избранных',
    addedToCompare: 'Добавлено в сравнение',
    excludedFromCompare: 'Исключено из сравнения',
    dashboard: 'Главная панель',
    login: 'Вход',
    registration: 'Регистрация',
    home: 'Главная',
    shop: 'Магазин',
    products: 'Товары',
    tea: 'Чай',
    coffee: 'Кофе',
    favorites: 'Избранные',
    compare: 'Сравнение',
    cart: 'Корзина',
    blog: 'Блог',
    club: 'Клуб',
    account: 'Аккаунт',
    lk: 'Личный кабинет',
    search: 'Поиск',
    logout: 'Выход',
    darkTheme: 'Тёмная тема',
    lightTheme: 'Светлая тема',
    sorting: 'Сортировка',
    new: 'Новые',
    pop: 'Популярные',
    priceAsc: 'Возрастание цены',
    priceDesc: 'Убывание цены',
    required: 'Обязательно',
    title: 'Заголовок',
    description: 'Описание',
    inStock: 'В наличии',
    ended: 'Закончился',
    volume: 'Объём',
    price: 'Цена',
    image: 'Изображение',
    images: 'Изображения',
    save: 'Сохранить',
    delete: 'Удалить',
    newProduct: 'Новый товар',
    maxSize: 'Максимальный размер',
    MaxLimit: 'Максимальное количество',
    more0: 'Нужно больше 0',
    published: 'Опубликовать',
    updateProduct: 'Обновление товара',
    reviews: 'Отзывы',
    homeTitle: 'Международное сообщество',
    homeDescription:
      'Добро пожаловать в сообщество ONE. Здесь нас интересует забота о здоровье, красоте и долголетии. Все пользователи имеют доступ к таким сервисам, как интернет-магазин, блог, социальная сеть. С каждым днем нас становится больше. Мы будем рады видеть вас в сообществе и помочь вам в достижении ваших целей.',
    policy: 'Политика конфиденциальности',
    cookies: 'Использование файлов cookie',
    quantity: 'Количество',
    cost: 'Стоимость',
    empty: 'Пусто',
    email: 'Email',
    password: 'Пароль',
    send: 'Отправить',
    min8: 'Минимум 8 символов',
    max32: 'Максимум 32 символа',
    dontAccount: 'Нет аккаунта?',
    haveAccount: 'Есть аккаунт?',
    invalidCredentials: 'Неверные учетные данные',
    maximum: 'Максимум',
    minimum: 'Минимум',
    profile: 'Профиль',
  },
}

export type TranslationKeys = keyof (typeof translate)['en']
