import { Suspense } from 'react'
import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import { Providers } from '@/providers'
import { Layout } from '@/ui'
import '../assets/styles/globals.css'
import { Header } from './_elements'

const jost = Jost({ weight: '500', subsets: ['latin'], display: 'swap' })

export const metadata: Metadata = {
  title: 'One',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Providers>
          <Suspense>
            <Header />
          </Suspense>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  )
}
