import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { headers } from 'next/headers'
import { redirect } from 'next/navigation'
import { authOptions } from '@/configs'

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
}

export default async function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)
  const headersList = headers()
  const fullUrl = headersList.get('referer') || ''
  const searchParams = new URL(fullUrl).searchParams
  const callbackUrl = searchParams.get('callbackUrl')
  const from = searchParams.get('from') || '/account'

  if (session?.user) {
    return redirect(callbackUrl || from)
  }

  return children
}
