import type { Metadata } from 'next'
import Link from 'next/link'
import { Aside, List, Widget } from '@/ui'

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
}

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Aside>
        <Widget>
          <List>
            <Link href={'/admin'}>Dashboard</Link>
            <Link href={'/admin/products'}>Products</Link>
          </List>
        </Widget>
      </Aside>
      {children}
    </>
  )
}
