import type { Metadata } from 'next'
import { Icon } from '@/ui'
import { ShopMenu, Sorting } from './_elements'
import styles from './page.module.css'

export const metadata: Metadata = {
  title: 'Shop',
  description: 'Generated by create next app',
}

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className={styles.layout}>
      <div className={styles.header}>
        <ShopMenu />

        <div className={styles.group}>
          <Sorting />

          <div className={styles.groupItem}>
            <Icon name="filter" width={25} height={25} /> Filter
          </div>
        </div>
      </div>
      {children}
    </div>
  )
}
