import type { Metadata } from 'next'
import Link from 'next/link'
import { Aside, Layout, Widget } from '@/ui'

export const metadata: Metadata = {
  title: 'Account',
  description: 'Generated by create next app',
}

export default function AccountLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Aside>
        <Widget>
          <Link href={'/account'}>Profile</Link>
        </Widget>
      </Aside>
      {children}
    </>
  )
}
